- name: Deploy application
  hosts: webservers
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
    - name: Ensure Docker Compose is installed
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-`uname -s`-`uname -m`
        dest: /usr/local/bin/docker-compose
        mode: '0755'
    - name: Pull latest Docker image
      command: docker pull bmi-app-image
    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /path/to/docker-compose
